### ISSUE TITLE
Linux doesn't build locally

### ISSUE THREAD

**Issue by JoseDiazRohena** [tote-bag-labs/valentine#14]
I've received a report that Valentine won't build on Linux, 
even though it builds on CI. This is likely because of casing
disagreements between includes file names (symlink 
include name->filename fixes the issue). These should
be cleaned up.

**Comment by tank-trax** [comment]
VST3 loads in Bitwig, but not in Reaper, Carla or Waveform

plugin validator gives

Started validating: ~/.vst3/Valentine.vst3/Contents/x86_64-linux/Valentine.so
Random seed: 0x60c9008
Validation started
Strictness level: 5
-----------------------------------------------------------------
Starting tests in: pluginval / Scan for plugins located in: ~/.vst3/Valentine.vst3/Contents/x86_64-linux/Valentine.so...
Num plugins found: 0
!!! Test 1 failed: No types found. This usually means the plugin binary is missing or damaged, an incompatible format or that it is an AU that isn't found by macOS so can't be created.
FAILED!!  1 test failed, out of a total of 1
*** FAILED

**Comment by JoseDiazRohena** [comment]
> same thing here, trying to build @baconpaul's Linux fix
> 
> ```
> CMake Error at libs/JUCE/extras/Build/CMake/JUCEUtils.cmake:1803 (add_library):
>   Cannot find source file:
> 
>     libs/tote_bag/juce_gui/LookAndFeel/LookAndFeel.h
> Call Stack (most recent call first):
>   CMakeLists.txt:47 (juce_add_plugin)
> ```
> 
> ```
> ~/dev/developers/baconpaul/valentine/libs/tote_bag/juce_gui$ ls -l
> total 16
> drwxrwxr-x 4 studio studio 4096 Apr  3 17:18 components
> drwxrwxr-x 2 studio studio 4096 Apr  3 17:18 lookandfeel
> drwxrwxr-x 2 studio studio 4096 Apr  3 17:18 managers
> drwxrwxr-x 2 studio studio 4096 Apr  3 17:18 utilities
> ```
> 
> this patch fixes it [01-Valentine.patch.zip](https://github.com/Tote-Bag-Labs/valentine/files/11143630/01-Valentine.patch.zip)|
> 
> ```
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index 2f5c26a..d817b1c 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -105,18 +105,18 @@ set(SourceFiles
>      libs/tote_bag/juce_gui/components/widgets/ParameterSlider.cpp
>      libs/tote_bag/juce_gui/components/widgets/ParameterTextButton.cpp
>  
> -    libs/tote_bag/juce_gui/LookAndFeel/LookAndFeel.h
> -    libs/tote_bag/juce_gui/LookAndFeel/LookAndFeelConstants.h
> -    libs/tote_bag/juce_gui/LookAndFeel/MeterLookAndFeelMethods.h
> -    libs/tote_bag/juce_gui/LookAndFeel/LookAndFeel.cpp
> -
> -    libs/tote_bag/juce_gui/Managers/ToteBagPresetManager.h
> -    libs/tote_bag/juce_gui/Managers/RadioButtonGroupManager.h
> -    libs/tote_bag/juce_gui/Managers/ToteBagPresetManager.cpp
> -    libs/tote_bag/juce_gui/Managers/RadioButtonGroupManager.cpp
> -
> -    libs/tote_bag/juce_gui/Utilities/GraphicsUtilities.h
> -    libs/tote_bag/juce_gui/Utilities/GraphicsUtilities.cpp
> +    libs/tote_bag/juce_gui/lookandfeel/LookAndFeel.h
> +    libs/tote_bag/juce_gui/lookandfeel/LookAndFeelConstants.h
> +    libs/tote_bag/juce_gui/lookandfeel/MeterLookAndFeelMethods.h
> +    libs/tote_bag/juce_gui/lookandfeel/LookAndFeel.cpp
> +
> +    libs/tote_bag/juce_gui/managers/ToteBagPresetManager.h
> +    libs/tote_bag/juce_gui/managers/RadioButtonGroupManager.h
> +    libs/tote_bag/juce_gui/managers/ToteBagPresetManager.cpp
> +    libs/tote_bag/juce_gui/managers/RadioButtonGroupManager.cpp
> +
> +    libs/tote_bag/juce_gui/utilities/GraphicsUtilities.h
> +    libs/tote_bag/juce_gui/utilities/GraphicsUtilities.cpp
>      )
>  
>  target_sources("${PROJECT_NAME}" PRIVATE ${SourceFiles})
> ```

This should be fixed in `valentine/main`.

**Comment by JoseDiazRohena** [comment]
> VST3 loads in Bitwig, but not in Reaper, Carla or Waveform
> 
> plugin validator gives
> 
> ```
> Started validating: ~/.vst3/Valentine.vst3/Contents/x86_64-linux/Valentine.so
> Random seed: 0x60c9008
> Validation started
> Strictness level: 5
> -----------------------------------------------------------------
> Starting tests in: pluginval / Scan for plugins located in: ~/.vst3/Valentine.vst3/Contents/x86_64-linux/Valentine.so...
> Num plugins found: 0
> !!! Test 1 failed: No types found. This usually means the plugin binary is missing or damaged, an incompatible format or that it is an AU that isn't found by macOS so can't be created.
> FAILED!!  1 test failed, out of a total of 1
> *** FAILED
> ```

Thank you for the report. I'll take a look once I learn how to spin up a Linux machine.

**Comment by JoseDiazRohena** [comment]
If you can confirm that it's building for you from `main`, I'll close this issue and open a new one for the plugin not showing up in some DAWs on Linux.

**Comment by baconpaul** [comment]
it built for me fine on both main and my branch on linux (and my branch passes plugin val on my machine and also in ci with stripped back). if that helps

**Comment by tank-trax** [comment]
I can confirm that main -> commit 62f98be builds and loads in Reaper, Waveform, Carla and Bitwig.

VST3 passes Waveform's built-in plugin validator.

If I may recommend, adding JACK_JUCE=1 for the Standalone

**Comment by JoseDiazRohena** [comment]
Thank you! What does JACK_JUCE=1 do?

**Comment by baconpaul** [comment]
It will make the executable link to jack for io in the standalone letting you use it in various internal routing and io. It’s kinda like turning on wasapi or asio on windows
