### ISSUE TITLE
AU Doesn't work in Logic

### ISSUE THREAD

**Issue by JoseDiazRohena** [Tote-Bag-Labs/valentine#16]
Valentine AU loads fine in Logic, but manipulating its controls has no effect on the signal. Signal seems to pass through unaffected, and is shown in Valentine's meters.

AU works as expected in Live.

**Comment by JoseDiazRohena** [comment]
Fixed in - https://github.com/Tote-Bag-Labs/valentine/pull/18

**Comment by baconpaul** [comment]
👍
