### ISSUE TITLE
A glyph leak in Linux

### ISSUE THREAD

**Issue by JoseDiazRohena** [tote-bag-labs/valentine#27]
> If you do a debug build, you run the standalone and then quit the juce leak detector will give you a leak message. The fact that it is a glyph means you somewhere assign a font to a static or a pointer which leaks or some such.

I bet it has something to do with https://forum.juce.com/t/lookandfeel-custom-fonts-linux-leaks/53914/5

There's an interesting solution posed here: https://forum.juce.com/t/only-loading-fonts-once-in-a-plugin/49564

Storing fonts in struct deriving from a special juce base class that deletes derived instances on exit...might see about that.

**Comment by baconpaul** [comment]
yeah so we used to do that.

We changed our strategy to have fonts live with the skin manager after XT 1.0 but in XT 1.0 we had a global delete on exit font manager object. Here's the code back then

https://github.com/surge-synthesizer/surge/blob/1edd725e51c236022d5f4cbc939e68453de15af4/src/surge-xt/gui/RuntimeFont.h#L12

**Comment by JoseDiazRohena** [comment]
Thank you for this!
